package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"reflect"
	"strings"
)

const FILE_NAME string = "auto_generated.go"

func writeGolangStruct(jsonData map[string]any) error {
	autoGeneratedFile, err := os.Create(FILE_NAME)
	if err != nil {
		log.Println("could not generate file .go")
		os.Exit(1)
	}

	autoGeneratedFile.WriteString("package auto_generated\n\n")
	autoGeneratedFile.WriteString("type AutoGenerated struct {\n")

	generatedStruct := ""
	for key, value := range jsonData {
		generatedStruct = fmt.Sprintf("    %s %v `json:'%s,omitempty'`",
			key, reflect.TypeOf(value), strings.ToLower(key),
		)
		autoGeneratedFile.WriteString(fmt.Sprintf("%s\n", generatedStruct))
	}
	autoGeneratedFile.WriteString("}")

	// TODO: work on this...
	file, err := os.ReadFile(FILE_NAME)
	if err != nil {
		return err
	}
	formatedFile := string(file)
	formatedFile = strings.ReplaceAll(formatedFile, "'", `"`)

	autoGeneratedFile.WriteString(formatedFile)

	return nil
}

func validJson(fileName string) bool {
	return strings.HasSuffix(fileName, ".json")
}

func readJsonFile(fileName string) ([]byte, error) {
	return os.ReadFile(fileName)
}

func main() {
	jsonFileName := os.Args[1]
	fmt.Println(jsonFileName)

	if !validJson(jsonFileName) {
		log.Println("invalid json file name")
		os.Exit(1)
	}

	out, err := readJsonFile(jsonFileName)
	if err != nil {
		log.Println("could not read json file")
		os.Exit(1)
	}

	var jsonData map[string]any
	err = json.Unmarshal(out, &jsonData)
	if err != nil {
		log.Println("could not unmarshal")
		os.Exit(1)
	}

	if err = writeGolangStruct(jsonData); err != nil {
		log.Println("could not write golang struct")
		os.Exit(1)
	}
}
