package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"reflect"
	"strings"
)

const FILE_NAME string = "auto_generated.go"

func validJsonExtension(fileName string) bool {
	return strings.HasSuffix(fileName, ".json")
}

func readJsonFile(fileName string) ([]byte, error) {
	return os.ReadFile(fileName)
}

func writeGolangStruct(jsonData map[string]interface{}) error {
	autoGeneratedFile, err := os.Create(FILE_NAME)
	if err != nil {
		log.Println("could not generate file .go")
		return err
	}

	autoGeneratedFile.WriteString("package auto_generated\n\n")
	autoGeneratedFile.WriteString("type AutoGenerated struct {\n")

	var autoGeneratedStruct string
	for key, value := range jsonData {
		publicField := fmt.Sprint(strings.ToUpper(string(key[0])) + key[1:])
		autoGeneratedStruct = fmt.Sprintf("    %s %v `json:'%s,omitempty'`",
			publicField, reflect.TypeOf(value), strings.ToLower(key),
		)
		autoGeneratedStruct = strings.ReplaceAll(autoGeneratedStruct, "'", `"`)

		autoGeneratedFile.WriteString(fmt.Sprintf("%s\n", autoGeneratedStruct))
	}
	autoGeneratedFile.WriteString("}")
	return nil
}

func main() {
	jsonFileName := os.Args[1]

	if !validJsonExtension(jsonFileName) {
		log.Println("invalid json file name, ensure that file has '.json' suffix")
		os.Exit(1)
	}

	jsonBytes, err := readJsonFile(jsonFileName)
	if err != nil {
		log.Println("could not read json file, checkout file name or path")
		os.Exit(1)
	}

	var jsonData map[string]interface{}
	err = json.Unmarshal(jsonBytes, &jsonData)
	if err != nil {
		log.Println("could not unmarshal, probably is not a valid json data")
		os.Exit(1)
	}

	if err = writeGolangStruct(jsonData); err != nil {
		log.Println("could not write golang struct")
		os.Exit(1)
	}
}
